### ISSUE TITLE
Model and the number of GPUs used to acquire the trained model for teaser image.

### ISSUE THREAD

**Issue by mch5048** [stelzner/osrt#1]
Hi, thanks for reproducing this interesting work.
I am curious about the training setup of the reproduced model, as the original OSRT model is computation-hungry that requires 64 TPUs.
This model is implemented in Pytorch, but the config file seems to set to 256 batch size which is on part with the original model (though the number of sampling rays are 1/4).

Thanks in advance!

**Comment by stelzner** [comment]
Hi, we ran the model as defined in the [config file](https://github.com/stelzner/osrt/blob/main/runs/msn/osrt/config.yaml) using a DGX machine with 8 A100 GPUs with 80GB VRAM each. I've added that information to the README.

**Comment by mch5048** [comment]
I see. Thanks for the quick response.
