### ISSUE TITLE
CommandException: No URLs matched: gs://kubric-public/tfds/kubric-frames/multi_shapenet_conditional/2.8.0/

### ISSUE THREAD

**Issue by leviome** [stelzner/osrt#4]
thanks for nice sharing! please help me with this exception.

**Comment by mch5048** [comment]
I managed to download the dataset via this command `gsutil -m cp -r "gs://kubric-public/tfds/kubric_frames/multi_shapenet_conditional/2.8.0"  . `

It will download the whole dataset at the current folder. So please modify the command at your need.

**Comment by stelzner** [comment]
Thanks for pointing this out - in the readme, I had mixed up an underscore with a dash. Fixed now.

**Comment by leviome** [comment]
Thanks. it's fixed!
