### ISSUE TITLE
Code cannot be git cloned or downloaded 

### ISSUE THREAD

**Issue by ychgoaround** [stelzner/osrt#6]
Hi,

Thanks for your work! However, I found that the code can not be git cloned or downloaded at the moment! Thanks!

Best

**Comment by stelzner** [comment]
Hi, it's working for me. Maybe some type of network outage? What happens if you run `git clone https://github.com/stelzner/osrt.git`? Have you tried downloading it in the browser?

**Comment by ychgoaround** [comment]
thanks, it is working now, it was some network issue
